import type { Metadata } from "next";


export const metadata: Metadata = {
    title: "Onboard",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <div className="main w-full h-full ">

            {children}
        </div>
    );
}
